.\"                                      Hey, EMACS: -*- nroff -*-
.TH VWP2 1 "December 9, 2017"
.SH NAME
vwp2 \- a visualization tool to compress an image file to a WP2 file
.SH SYNOPSIS
.B vwp2
.RI [ options ] " input_file
.br
.SH DESCRIPTION
This manual page documents the
.B vwp2
command.
.PP
\fBvwp2\fP compresses an image using the WP2 format.
Input format can be either PNG, JPEG, TIFF, PNM.
.SH OPTIONS
The basic options are:
.TP

.SH SEE ALSO
.BR cwp2 (1), dwp2 (1),
.br
Please refer to http://developers.google.com/speed/webp/ for additional
information.
